<a href="https://colab.research.google.com/github/Shubh23104/Encryptix/blob/main/Bank_Customer_Curn_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv("Churn_Modelling.csv")

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.drop(['RowNumber'], axis=1, inplace= True)

In [5]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [6]:
df= df.join(pd.get_dummies(df['Geography'], prefix= 'Geo').astype('int'))

In [7]:
df.drop(['Geography'], axis=1, inplace= True)

In [8]:
df.head()

CustomerId   Surname  CreditScore  Gender  Age  Tenure    Balance  \
0    15634602  Hargrave          619  Female   42       2       0.00   
1    15647311      Hill          608  Female   41       1   83807.86   
2    15619304      Onio          502  Female   42       8  159660.80   
3    15701354      Boni          699  Female   39       1       0.00   
4    15737888  Mitchell          850  Female   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  \
0              1          1               1        101348.88       1   
1              1          0               1        112542.58       0   
2              3          1               0        113931.57       1   
3              2          0               0         93826.63       0   
4              1          1               1         79084.10       0   

   Geo_France  Geo_Germany  Geo_Spain  
0           1            0          0  
1           0            0          1  
2           1            0          0  
3           1            0          0  
4           0            0          1

In [9]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [10]:
df['Gender']= df['Gender'].astype('str').apply(lambda x: 1 if x=='Female' else 0)

In [11]:
df['Gender'].value_counts()

Gender
0    5457
1    4543
Name: count, dtype: int64

In [12]:
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited', 'Geo_France', 'Geo_Germany', 'Geo_Spain'],
      dtype='object')

In [13]:
df= df[['CustomerId', 'Surname', 'CreditScore', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Geo_France', 'Geo_Germany', 'Geo_Spain', 'Exited']]
df.head()

CustomerId   Surname  CreditScore  Gender  Age  Tenure    Balance  \
0    15634602  Hargrave          619       1   42       2       0.00   
1    15647311      Hill          608       1   41       1   83807.86   
2    15619304      Onio          502       1   42       8  159660.80   
3    15701354      Boni          699       1   39       1       0.00   
4    15737888  Mitchell          850       1   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Geo_France  \
0              1          1               1        101348.88           1   
1              1          0               1        112542.58           0   
2              3          1               0        113931.57           1   
3              2          0               0         93826.63           1   
4              1          1               1         79084.10           0   

   Geo_Germany  Geo_Spain  Exited  
0            0          0       1  
1            0          1       0  
2            0          0       1  
3            0          0       0  
4            0          1       0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CustomerId       10000 non-null  int64  
 1   Surname          10000 non-null  object 
 2   CreditScore      10000 non-null  int64  
 3   Gender           10000 non-null  int64  
 4   Age              10000 non-null  int64  
 5   Tenure           10000 non-null  int64  
 6   Balance          10000 non-null  float64
 7   NumOfProducts    10000 non-null  int64  
 8   HasCrCard        10000 non-null  int64  
 9   IsActiveMember   10000 non-null  int64  
 10  EstimatedSalary  10000 non-null  float64
 11  Geo_France       10000 non-null  int64  
 12  Geo_Germany      10000 non-null  int64  
 13  Geo_Spain        10000 non-null  int64  
 14  Exited           10000 non-null  int64  
dtypes: float64(2), int64(12), object(1)
memory usage: 1.1+ MB


In [15]:
df.duplicated().sum()

0

In [16]:
df[['CreditScore', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Geo_France', 'Geo_Germany', 'Geo_Spain', 'Exited']].corr().style.background_gradient(cmap='coolwarm')

In [17]:
X= df[['CreditScore', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Geo_France', 'Geo_Germany', 'Geo_Spain']]
y= df['Exited']

In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import  train_test_split
sc= StandardScaler()
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2)
X_train_scld= sc.fit_transform(X_train)
X_test_scld= sc.transform(X_test)

In [19]:
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression()
lr.fit(X_train_scld, y_train)
y_pred_lr= lr.predict(X_test_scld)
y_pred_lr

array([0, 0, 0, ..., 0, 0, 0])

In [20]:
from sklearn.metrics import accuracy_score
acc_lr= accuracy_score(y_test, y_pred_lr)
acc_lr

0.813

In [21]:
from sklearn.metrics import confusion_matrix
cm= pd.DataFrame(confusion_matrix(y_test, y_pred_lr))
cm

0   1
0  1541  61
1   313  85

In [22]:
from sklearn.ensemble import RandomForestClassifier
rfc= RandomForestClassifier(n_estimators=100, criterion='gini')
rfc.fit(X_train_scld, y_train)
y_pred_rfc= rfc.predict(X_test_scld)
y_pred_rfc

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
from sklearn.metrics import accuracy_score
acc_rfc= accuracy_score(y_test, y_pred_rfc)
acc_rfc

0.8625

In [24]:
from sklearn.metrics import confusion_matrix
cm_rfc= confusion_matrix(y_test, y_pred_rfc)
cm_rfc= pd.DataFrame(cm_rfc)
cm_rfc

0    1
0  1548   54
1   221  177

In [25]:
from sklearn.svm import SVC
svc= SVC(kernel= 'rbf', probability=True)
svc.fit(X_train_scld, y_train)
y_pred_svc= svc.predict(X_test_scld)
y_pred_svc

array([0, 0, 0, ..., 0, 0, 0])

In [26]:
from sklearn.metrics import accuracy_score
acc_svc= accuracy_score(y_test, y_pred_svc)
acc_svc

0.855

In [27]:
from sklearn.metrics import confusion_matrix
cm_svc= confusion_matrix(y_test, y_pred_svc)
cm_svc= pd.DataFrame(cm_svc)
cm_svc

0    1
0  1563   39
1   251  147