<a href="https://colab.research.google.com/github/Shubh23104/Encryptix/blob/main/Task-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df= pd.read_csv("Churn_Modelling.csv")

In [ ]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
df.drop(['RowNumber'], axis=1, inplace= True)

In [ ]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [ ]:
df= df.join(pd.get_dummies(df['Geography'], prefix= 'Geo').astype('int'))

In [ ]:
df.drop(['Geography'], axis=1, inplace= True)

In [ ]:
df.head()

CustomerId   Surname  CreditScore  Gender  Age  Tenure    Balance  \
0    15634602  Hargrave          619  Female   42       2       0.00   
1    15647311      Hill          608  Female   41       1   83807.86   
2    15619304      Onio          502  Female   42       8  159660.80   
3    15701354      Boni          699  Female   39       1       0.00   
4    15737888  Mitchell          850  Female   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  \
0              1          1               1        101348.88       1   
1              1          0               1        112542.58       0   
2              3          1               0        113931.57       1   
3              2          0               0         93826.63       0   
4              1          1               1         79084.10       0   

   Geo_France  Geo_Germany  Geo_Spain  
0           1            0          0  
1           0            0          1  
2           1            0          0  
3           1            0          0  
4           0            0          1

In [ ]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [ ]:
df['Gender']= df['Gender'].astype('str').apply(lambda x: 1 if x=='Female' else 0)

In [ ]:
df['Gender'].value_counts()

Gender
0    5457
1    4543
Name: count, dtype: int64

In [ ]:
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited', 'Geo_France', 'Geo_Germany', 'Geo_Spain'],
      dtype='object')

In [ ]:
df= df[['CustomerId', 'Surname', 'CreditScore', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Geo_France', 'Geo_Germany', 'Geo_Spain', 'Exited']]
df.head()

CustomerId   Surname  CreditScore  Gender  Age  Tenure    Balance  \
0    15634602  Hargrave          619       1   42       2       0.00   
1    15647311      Hill          608       1   41       1   83807.86   
2    15619304      Onio          502       1   42       8  159660.80   
3    15701354      Boni          699       1   39       1       0.00   
4    15737888  Mitchell          850       1   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Geo_France  \
0              1          1               1        101348.88           1   
1              1          0               1        112542.58           0   
2              3          1               0        113931.57           1   
3              2          0               0         93826.63           1   
4              1          1               1         79084.10           0   

   Geo_Germany  Geo_Spain  Exited  
0            0          0       1  
1            0          1       0  
2            0          0       1  
3            0          0       0  
4            0          1       0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CustomerId       10000 non-null  int64  
 1   Surname          10000 non-null  object 
 2   CreditScore      10000 non-null  int64  
 3   Gender           10000 non-null  int64  
 4   Age              10000 non-null  int64  
 5   Tenure           10000 non-null  int64  
 6   Balance          10000 non-null  float64
 7   NumOfProducts    10000 non-null  int64  
 8   HasCrCard        10000 non-null  int64  
 9   IsActiveMember   10000 non-null  int64  
 10  EstimatedSalary  10000 non-null  float64
 11  Geo_France       10000 non-null  int64  
 12  Geo_Germany      10000 non-null  int64  
 13  Geo_Spain        10000 non-null  int64  
 14  Exited           10000 non-null  int64  
dtypes: float64(2), int64(12), object(1)
memory usage: 1.1+ MB


In [ ]:
df.duplicated().sum()

0

In [ ]:
df[['CreditScore', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Geo_France', 'Geo_Germany', 'Geo_Spain', 'Exited']].corr().style.background_gradient(cmap='coolwarm')

In [ ]:
X= df[['CreditScore', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Geo_France', 'Geo_Germany', 'Geo_Spain']]
y= df['Exited']

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import  train_test_split
sc= StandardScaler()
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2)
X_train_scld= sc.fit_transform(X_train)
X_test_scld= sc.transform(X_test)

***Logistic Regression***

In [ ]:
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression()
lr.fit(X_train_scld, y_train)
y_pred_lr= lr.predict(X_test_scld)
y_pred_lr

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score
acc_lr= accuracy_score(y_test, y_pred_lr)
acc_lr

0.8075

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.82      0.96      0.89      1579
           1       0.62      0.23      0.33       421

    accuracy                           0.81      2000
   macro avg       0.72      0.60      0.61      2000
weighted avg       0.78      0.81      0.77      2000



***Random Forest***

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc= RandomForestClassifier(n_estimators=100, criterion='gini')
rfc.fit(X_train_scld, y_train)
y_pred_rfc= rfc.predict(X_test_scld)
y_pred_rfc

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
from sklearn.metrics import accuracy_score
acc_rfc= accuracy_score(y_test, y_pred_rfc)
acc_rfc

0.864

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_rfc))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1579
           1       0.80      0.48      0.60       421

    accuracy                           0.86      2000
   macro avg       0.84      0.72      0.76      2000
weighted avg       0.86      0.86      0.85      2000



***Support Vector Classifier***

In [ ]:
from sklearn.svm import SVC
svc= SVC(kernel= 'rbf', probability=True)
svc.fit(X_train_scld, y_train)
y_pred_svc= svc.predict(X_test_scld)
y_pred_svc

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
from sklearn.metrics import accuracy_score
acc_svc= accuracy_score(y_test, y_pred_svc)
acc_svc

0.859

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_svc))

              precision    recall  f1-score   support

           0       0.86      0.98      0.92      1579
           1       0.84      0.41      0.55       421

    accuracy                           0.86      2000
   macro avg       0.85      0.69      0.73      2000
weighted avg       0.86      0.86      0.84      2000

